CREATE TABLE [dbo].[persons] (
    [personId]                  INT IDENTITY (1, 1)                           PRIMARY KEY NOT NULL,
    [personTitle]               NVARCHAR (30)                                 NOT NULL,
    [personFirstName]           NVARCHAR (50)                                 NOT NULL,
    [personLastName]            NVARCHAR (50)                                 NOT NULL,
    [personAddressStreet]       NVARCHAR (199)                                NOT NULL,
    [personAddressStreetExt]    NVARCHAR (100)                                NULL,
    [personAddressZipCode]      NVARCHAR (10)                                 NOT NULL,
    [PersonAddressCity]         NVARCHAR (100)                                NOT NULL,
    [personAddressCountry]      NVARCHAR (50)                                 CONSTRAINT [personAddressCountry] NOT NULL,
    [personAddressRegion]       NVARCHAR (50)                                 NULL,
    [personAddressIsValid]      BIT                                           CONSTRAINT [personAddressIsValid] DEFAULT 0 NOT NULL,
    [personPhoneNumber]         NVARCHAR (50)                                 NOT NULL,
    [personPhoneNumberIsValid]  BIT                                           CONSTRAINT [personPhoneNumberIsValid] DEFAULT 0 NOT NULL,
    [personEmailAddress]        NVARCHAR (100)                                NOT NULL,
    [personEmailAddressIsValid] BIT                                           CONSTRAINT [personEmailAddressIsValid] DEFAULT 0 NOT NULL,
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'City', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'PersonAddressCity';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Email has been validated', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personEmailAddressIsValid';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Phone number', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personPhoneNumber';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Street extension', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personAddressStreetExt';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Address has been validated', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personAddressIsValid';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'ZIP', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personAddressZipCode';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Title', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personTitle';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Firstname', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personFirstName';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Region', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personAddressRegion';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Street', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personAddressStreet';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Email address', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personEmailAddress';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier generated by system', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personId';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Lastname', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personLastName';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Phone has been validated', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personPhoneNumberIsValid';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Country of residence', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'persons', @level2type = N'COLUMN', @level2name = N'personAddressCountry';
